// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: mcpanel.proto

package mcpanel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_Register_FullMethodName               = "/mcpanel.DaemonService/Register"
	DaemonService_Ping_FullMethodName                   = "/mcpanel.DaemonService/Ping"
	DaemonService_CreateInstance_FullMethodName         = "/mcpanel.DaemonService/CreateInstance"
	DaemonService_StartInstance_FullMethodName          = "/mcpanel.DaemonService/StartInstance"
	DaemonService_StopInstance_FullMethodName           = "/mcpanel.DaemonService/StopInstance"
	DaemonService_KillInstance_FullMethodName           = "/mcpanel.DaemonService/KillInstance"
	DaemonService_RestartInstance_FullMethodName        = "/mcpanel.DaemonService/RestartInstance"
	DaemonService_DeleteInstance_FullMethodName         = "/mcpanel.DaemonService/DeleteInstance"
	DaemonService_GetInstanceStatus_FullMethodName      = "/mcpanel.DaemonService/GetInstanceStatus"
	DaemonService_GetInstanceRuntime_FullMethodName     = "/mcpanel.DaemonService/GetInstanceRuntime"
	DaemonService_GetContainerCapability_FullMethodName = "/mcpanel.DaemonService/GetContainerCapability"
	DaemonService_SetInstanceContainer_FullMethodName   = "/mcpanel.DaemonService/SetInstanceContainer"
	DaemonService_Console_FullMethodName                = "/mcpanel.DaemonService/Console"
	DaemonService_StreamMetrics_FullMethodName          = "/mcpanel.DaemonService/StreamMetrics"
	DaemonService_ListFiles_FullMethodName              = "/mcpanel.DaemonService/ListFiles"
	DaemonService_ReadFile_FullMethodName               = "/mcpanel.DaemonService/ReadFile"
	DaemonService_WriteFile_FullMethodName              = "/mcpanel.DaemonService/WriteFile"
	DaemonService_DeleteFile_FullMethodName             = "/mcpanel.DaemonService/DeleteFile"
	DaemonService_Mkdir_FullMethodName                  = "/mcpanel.DaemonService/Mkdir"
	DaemonService_RenameFile_FullMethodName             = "/mcpanel.DaemonService/RenameFile"
	DaemonService_CopyFile_FullMethodName               = "/mcpanel.DaemonService/CopyFile"
	DaemonService_SearchFiles_FullMethodName            = "/mcpanel.DaemonService/SearchFiles"
	DaemonService_DownloadFile_FullMethodName           = "/mcpanel.DaemonService/DownloadFile"
	DaemonService_GetInstanceIcon_FullMethodName        = "/mcpanel.DaemonService/GetInstanceIcon"
	DaemonService_GetMetrics_FullMethodName             = "/mcpanel.DaemonService/GetMetrics"
	DaemonService_SubmitJob_FullMethodName              = "/mcpanel.DaemonService/SubmitJob"
	DaemonService_GetJob_FullMethodName                 = "/mcpanel.DaemonService/GetJob"
	DaemonService_CancelJob_FullMethodName              = "/mcpanel.DaemonService/CancelJob"
	DaemonService_GetPlayerOverview_FullMethodName      = "/mcpanel.DaemonService/GetPlayerOverview"
	DaemonService_SendCommand_FullMethodName            = "/mcpanel.DaemonService/SendCommand"
	DaemonService_ListResources_FullMethodName          = "/mcpanel.DaemonService/ListResources"
	DaemonService_UploadResource_FullMethodName         = "/mcpanel.DaemonService/UploadResource"
	DaemonService_DeleteResource_FullMethodName         = "/mcpanel.DaemonService/DeleteResource"
	DaemonService_ListJavaRuntimes_FullMethodName       = "/mcpanel.DaemonService/ListJavaRuntimes"
	DaemonService_GetConfig_FullMethodName              = "/mcpanel.DaemonService/GetConfig"
	DaemonService_SetConfig_FullMethodName              = "/mcpanel.DaemonService/SetConfig"
	DaemonService_UploadJar_FullMethodName              = "/mcpanel.DaemonService/UploadJar"
	DaemonService_SetInstanceJar_FullMethodName         = "/mcpanel.DaemonService/SetInstanceJar"
	DaemonService_ListJars_FullMethodName               = "/mcpanel.DaemonService/ListJars"
	DaemonService_Backup_FullMethodName                 = "/mcpanel.DaemonService/Backup"
	DaemonService_Restore_FullMethodName                = "/mcpanel.DaemonService/Restore"
	DaemonService_ListBackups_FullMethodName            = "/mcpanel.DaemonService/ListBackups"
	DaemonService_DeleteBackup_FullMethodName           = "/mcpanel.DaemonService/DeleteBackup"
	DaemonService_ApplyTunnel_FullMethodName            = "/mcpanel.DaemonService/ApplyTunnel"
	DaemonService_RemoveTunnel_FullMethodName           = "/mcpanel.DaemonService/RemoveTunnel"
	DaemonService_ListTunnels_FullMethodName            = "/mcpanel.DaemonService/ListTunnels"
	DaemonService_TestFrps_FullMethodName               = "/mcpanel.DaemonService/TestFrps"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Daemon 暴露的服务
type DaemonServiceClient interface {
	// 握手/注册：Daemon 启动后向 Panel 上报自身信息（节点能力）
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 心跳/状态上报
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// ---- 实例管理 ----
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	StartInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	StopInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	KillInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	RestartInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	GetInstanceStatus(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*InstanceStatus, error)
	GetInstanceRuntime(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*InstanceRuntime, error)
	// 容器化隔离：查询节点能力 / 开关某实例的容器化
	GetContainerCapability(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ContainerCapability, error)
	SetInstanceContainer(ctx context.Context, in *SetInstanceContainerRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// 控制台：双向流（Panel 发命令，Daemon 回日志/输出）
	Console(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleFrame, ConsoleFrame], error)
	// 监控数据流：Daemon -> Panel 持续推送
	StreamMetrics(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Metrics], error)
	// ---- 文件管理（实例目录） ----
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// 实例图标：节点按约定在实例目录里找 server-icon.png / icon.png 并流式回传。
	// 文件名约定放在 Daemon 侧 —— 面板不该知道节点上的文件名，
	// 也不用为此换成"面板猜文件名、失败了再猜另一个"的两次往返。
	GetInstanceIcon(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	GetMetrics(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*Metrics, error)
	// ---- 排队任务（压缩/解压等重 IO 操作） ----
	//
	// 这类操作耗时可达数分钟，且大量占用磁盘 IO。若像普通请求那样同步执行，
	// 既会拖住 HTTP 连接，也会让同一节点上的多个实例互相抢占资源。
	// 因此统一提交到 Daemon 的公共任务队列，由固定数量的 worker 串行消费。
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	GetJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error)
	CancelJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// ---- 玩家总览（历史玩家 / 游戏时长） ----
	GetPlayerOverview(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*PlayerOverviewResponse, error)
	// ---- 实例指令（供定时任务下发，无需打开控制台） ----
	SendCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// ---- 节点共享资源（管理员统一上传，本节点实例复用） ----
	ListResources(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	UploadResource(ctx context.Context, in *UploadResourceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// ---- 节点运行环境（实际安装的 JDK） ----
	ListJavaRuntimes(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListJavaRuntimesResponse, error)
	// 配置读写
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	SetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// 核心 jar 管理
	UploadJar(ctx context.Context, in *UploadJarRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	SetInstanceJar(ctx context.Context, in *SetInstanceJarRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	ListJars(ctx context.Context, in *ListJarsRequest, opts ...grpc.CallOption) (*ListJarsResponse, error)
	// 备份/回滚
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// ---- frp 隧道管理 ----
	ApplyTunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	RemoveTunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error)
	// 线路（frps）自检：在**本节点上**真的连一次并注册一个临时代理，随后撤掉。
	// 放在 Daemon 侧而不是面板侧：以后真正跑 frpc 的是节点，只有从节点测才作数
	// （面板能连通 ≠ 节点能连通）。
	TestFrps(ctx context.Context, in *TestFrpsRequest, opts ...grpc.CallOption) (*TestFrpsResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, DaemonService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DaemonService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) KillInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_KillInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RestartInstance(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_RestartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_DeleteInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetInstanceStatus(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*InstanceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceStatus)
	err := c.cc.Invoke(ctx, DaemonService_GetInstanceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetInstanceRuntime(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*InstanceRuntime, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceRuntime)
	err := c.cc.Invoke(ctx, DaemonService_GetInstanceRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetContainerCapability(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ContainerCapability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerCapability)
	err := c.cc.Invoke(ctx, DaemonService_GetContainerCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SetInstanceContainer(ctx context.Context, in *SetInstanceContainerRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_SetInstanceContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Console(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleFrame, ConsoleFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_Console_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsoleFrame, ConsoleFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_ConsoleClient = grpc.BidiStreamingClient[ConsoleFrame, ConsoleFrame]

func (c *daemonServiceClient) StreamMetrics(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Metrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[1], DaemonService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstanceRequest, Metrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamMetricsClient = grpc.ServerStreamingClient[Metrics]

func (c *daemonServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, DaemonService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, DaemonService_SearchFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[2], DaemonService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_DownloadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *daemonServiceClient) GetInstanceIcon(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[3], DaemonService_GetInstanceIcon_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstanceRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_GetInstanceIconClient = grpc.ServerStreamingClient[FileChunk]

func (c *daemonServiceClient) GetMetrics(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*Metrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Metrics)
	err := c.cc.Invoke(ctx, DaemonService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, DaemonService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, DaemonService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CancelJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetPlayerOverview(ctx context.Context, in *InstanceRequest, opts ...grpc.CallOption) (*PlayerOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerOverviewResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetPlayerOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SendCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListResources(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UploadResource(ctx context.Context, in *UploadResourceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_UploadResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListJavaRuntimes(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListJavaRuntimesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJavaRuntimesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListJavaRuntimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, DaemonService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UploadJar(ctx context.Context, in *UploadJarRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_UploadJar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SetInstanceJar(ctx context.Context, in *SetInstanceJarRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_SetInstanceJar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListJars(ctx context.Context, in *ListJarsRequest, opts ...grpc.CallOption) (*ListJarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJarsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListJars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, DaemonService_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ApplyTunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_ApplyTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RemoveTunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_RemoveTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTunnelsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) TestFrps(ctx context.Context, in *TestFrpsRequest, opts ...grpc.CallOption) (*TestFrpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestFrpsResponse)
	err := c.cc.Invoke(ctx, DaemonService_TestFrps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// Daemon 暴露的服务
type DaemonServiceServer interface {
	// 握手/注册：Daemon 启动后向 Panel 上报自身信息（节点能力）
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 心跳/状态上报
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// ---- 实例管理 ----
	CreateInstance(context.Context, *CreateInstanceRequest) (*OperationResponse, error)
	StartInstance(context.Context, *InstanceRequest) (*OperationResponse, error)
	StopInstance(context.Context, *InstanceRequest) (*OperationResponse, error)
	KillInstance(context.Context, *InstanceRequest) (*OperationResponse, error)
	RestartInstance(context.Context, *InstanceRequest) (*OperationResponse, error)
	DeleteInstance(context.Context, *DeleteInstanceRequest) (*OperationResponse, error)
	GetInstanceStatus(context.Context, *InstanceRequest) (*InstanceStatus, error)
	GetInstanceRuntime(context.Context, *InstanceRequest) (*InstanceRuntime, error)
	// 容器化隔离：查询节点能力 / 开关某实例的容器化
	GetContainerCapability(context.Context, *EmptyRequest) (*ContainerCapability, error)
	SetInstanceContainer(context.Context, *SetInstanceContainerRequest) (*OperationResponse, error)
	// 控制台：双向流（Panel 发命令，Daemon 回日志/输出）
	Console(grpc.BidiStreamingServer[ConsoleFrame, ConsoleFrame]) error
	// 监控数据流：Daemon -> Panel 持续推送
	StreamMetrics(*InstanceRequest, grpc.ServerStreamingServer[Metrics]) error
	// ---- 文件管理（实例目录） ----
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*OperationResponse, error)
	DeleteFile(context.Context, *FileRequest) (*OperationResponse, error)
	Mkdir(context.Context, *MkdirRequest) (*OperationResponse, error)
	RenameFile(context.Context, *RenameFileRequest) (*OperationResponse, error)
	CopyFile(context.Context, *CopyFileRequest) (*OperationResponse, error)
	SearchFiles(context.Context, *SearchFilesRequest) (*ListFilesResponse, error)
	DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error
	// 实例图标：节点按约定在实例目录里找 server-icon.png / icon.png 并流式回传。
	// 文件名约定放在 Daemon 侧 —— 面板不该知道节点上的文件名，
	// 也不用为此换成"面板猜文件名、失败了再猜另一个"的两次往返。
	GetInstanceIcon(*InstanceRequest, grpc.ServerStreamingServer[FileChunk]) error
	GetMetrics(context.Context, *InstanceRequest) (*Metrics, error)
	// ---- 排队任务（压缩/解压等重 IO 操作） ----
	//
	// 这类操作耗时可达数分钟，且大量占用磁盘 IO。若像普通请求那样同步执行，
	// 既会拖住 HTTP 连接，也会让同一节点上的多个实例互相抢占资源。
	// 因此统一提交到 Daemon 的公共任务队列，由固定数量的 worker 串行消费。
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJob(context.Context, *JobRequest) (*JobStatus, error)
	CancelJob(context.Context, *JobRequest) (*OperationResponse, error)
	// ---- 玩家总览（历史玩家 / 游戏时长） ----
	GetPlayerOverview(context.Context, *InstanceRequest) (*PlayerOverviewResponse, error)
	// ---- 实例指令（供定时任务下发，无需打开控制台） ----
	SendCommand(context.Context, *CommandRequest) (*OperationResponse, error)
	// ---- 节点共享资源（管理员统一上传，本节点实例复用） ----
	ListResources(context.Context, *EmptyRequest) (*ListResourcesResponse, error)
	UploadResource(context.Context, *UploadResourceRequest) (*OperationResponse, error)
	DeleteResource(context.Context, *DeleteResourceRequest) (*OperationResponse, error)
	// ---- 节点运行环境（实际安装的 JDK） ----
	ListJavaRuntimes(context.Context, *EmptyRequest) (*ListJavaRuntimesResponse, error)
	// 配置读写
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	SetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	// 核心 jar 管理
	UploadJar(context.Context, *UploadJarRequest) (*OperationResponse, error)
	SetInstanceJar(context.Context, *SetInstanceJarRequest) (*OperationResponse, error)
	ListJars(context.Context, *ListJarsRequest) (*ListJarsResponse, error)
	// 备份/回滚
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	Restore(context.Context, *RestoreRequest) (*OperationResponse, error)
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	DeleteBackup(context.Context, *DeleteBackupRequest) (*OperationResponse, error)
	// ---- frp 隧道管理 ----
	ApplyTunnel(context.Context, *TunnelRequest) (*OperationResponse, error)
	RemoveTunnel(context.Context, *TunnelRequest) (*OperationResponse, error)
	ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error)
	// 线路（frps）自检：在**本节点上**真的连一次并注册一个临时代理，随后撤掉。
	// 放在 Daemon 侧而不是面板侧：以后真正跑 frpc 的是节点，只有从节点测才作数
	// （面板能连通 ≠ 节点能连通）。
	TestFrps(context.Context, *TestFrpsRequest) (*TestFrpsResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDaemonServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDaemonServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedDaemonServiceServer) StartInstance(context.Context, *InstanceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedDaemonServiceServer) StopInstance(context.Context, *InstanceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedDaemonServiceServer) KillInstance(context.Context, *InstanceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillInstance not implemented")
}
func (UnimplementedDaemonServiceServer) RestartInstance(context.Context, *InstanceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartInstance not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteInstance(context.Context, *DeleteInstanceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInstance not implemented")
}
func (UnimplementedDaemonServiceServer) GetInstanceStatus(context.Context, *InstanceRequest) (*InstanceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstanceStatus not implemented")
}
func (UnimplementedDaemonServiceServer) GetInstanceRuntime(context.Context, *InstanceRequest) (*InstanceRuntime, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstanceRuntime not implemented")
}
func (UnimplementedDaemonServiceServer) GetContainerCapability(context.Context, *EmptyRequest) (*ContainerCapability, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainerCapability not implemented")
}
func (UnimplementedDaemonServiceServer) SetInstanceContainer(context.Context, *SetInstanceContainerRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInstanceContainer not implemented")
}
func (UnimplementedDaemonServiceServer) Console(grpc.BidiStreamingServer[ConsoleFrame, ConsoleFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Console not implemented")
}
func (UnimplementedDaemonServiceServer) StreamMetrics(*InstanceRequest, grpc.ServerStreamingServer[Metrics]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedDaemonServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedDaemonServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedDaemonServiceServer) WriteFile(context.Context, *WriteFileRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteFile(context.Context, *FileRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedDaemonServiceServer) Mkdir(context.Context, *MkdirRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedDaemonServiceServer) RenameFile(context.Context, *RenameFileRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedDaemonServiceServer) CopyFile(context.Context, *CopyFileRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedDaemonServiceServer) SearchFiles(context.Context, *SearchFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFiles not implemented")
}
func (UnimplementedDaemonServiceServer) DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedDaemonServiceServer) GetInstanceIcon(*InstanceRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetInstanceIcon not implemented")
}
func (UnimplementedDaemonServiceServer) GetMetrics(context.Context, *InstanceRequest) (*Metrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedDaemonServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedDaemonServiceServer) GetJob(context.Context, *JobRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedDaemonServiceServer) CancelJob(context.Context, *JobRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedDaemonServiceServer) GetPlayerOverview(context.Context, *InstanceRequest) (*PlayerOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerOverview not implemented")
}
func (UnimplementedDaemonServiceServer) SendCommand(context.Context, *CommandRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedDaemonServiceServer) ListResources(context.Context, *EmptyRequest) (*ListResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedDaemonServiceServer) UploadResource(context.Context, *UploadResourceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadResource not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteResource(context.Context, *DeleteResourceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedDaemonServiceServer) ListJavaRuntimes(context.Context, *EmptyRequest) (*ListJavaRuntimesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJavaRuntimes not implemented")
}
func (UnimplementedDaemonServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedDaemonServiceServer) SetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedDaemonServiceServer) UploadJar(context.Context, *UploadJarRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadJar not implemented")
}
func (UnimplementedDaemonServiceServer) SetInstanceJar(context.Context, *SetInstanceJarRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInstanceJar not implemented")
}
func (UnimplementedDaemonServiceServer) ListJars(context.Context, *ListJarsRequest) (*ListJarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJars not implemented")
}
func (UnimplementedDaemonServiceServer) Backup(context.Context, *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedDaemonServiceServer) Restore(context.Context, *RestoreRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedDaemonServiceServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedDaemonServiceServer) ApplyTunnel(context.Context, *TunnelRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyTunnel not implemented")
}
func (UnimplementedDaemonServiceServer) RemoveTunnel(context.Context, *TunnelRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTunnel not implemented")
}
func (UnimplementedDaemonServiceServer) ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedDaemonServiceServer) TestFrps(context.Context, *TestFrpsRequest) (*TestFrpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestFrps not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartInstance(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopInstance(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_KillInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).KillInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_KillInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).KillInstance(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RestartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RestartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RestartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RestartInstance(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteInstance(ctx, req.(*DeleteInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetInstanceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetInstanceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetInstanceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetInstanceStatus(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetInstanceRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetInstanceRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetInstanceRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetInstanceRuntime(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetContainerCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetContainerCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetContainerCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetContainerCapability(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SetInstanceContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstanceContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SetInstanceContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SetInstanceContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SetInstanceContainer(ctx, req.(*SetInstanceContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Console_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonServiceServer).Console(&grpc.GenericServerStream[ConsoleFrame, ConsoleFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_ConsoleServer = grpc.BidiStreamingServer[ConsoleFrame, ConsoleFrame]

func _DaemonService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).StreamMetrics(m, &grpc.GenericServerStream[InstanceRequest, Metrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamMetricsServer = grpc.ServerStreamingServer[Metrics]

func _DaemonService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CopyFile(ctx, req.(*CopyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SearchFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SearchFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SearchFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SearchFiles(ctx, req.(*SearchFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_DownloadFileServer = grpc.ServerStreamingServer[FileChunk]

func _DaemonService_GetInstanceIcon_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).GetInstanceIcon(m, &grpc.GenericServerStream[InstanceRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_GetInstanceIconServer = grpc.ServerStreamingServer[FileChunk]

func _DaemonService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetMetrics(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CancelJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetPlayerOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetPlayerOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetPlayerOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetPlayerOverview(ctx, req.(*InstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SendCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListResources(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UploadResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UploadResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UploadResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UploadResource(ctx, req.(*UploadResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListJavaRuntimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListJavaRuntimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListJavaRuntimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListJavaRuntimes(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UploadJar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadJarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UploadJar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UploadJar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UploadJar(ctx, req.(*UploadJarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SetInstanceJar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstanceJarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SetInstanceJar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SetInstanceJar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SetInstanceJar(ctx, req.(*SetInstanceJarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListJars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListJars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListJars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListJars(ctx, req.(*ListJarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ApplyTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ApplyTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ApplyTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ApplyTunnel(ctx, req.(*TunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RemoveTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RemoveTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RemoveTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RemoveTunnel(ctx, req.(*TunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListTunnels(ctx, req.(*ListTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_TestFrps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestFrpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).TestFrps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_TestFrps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).TestFrps(ctx, req.(*TestFrpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcpanel.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DaemonService_Register_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _DaemonService_Ping_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _DaemonService_CreateInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _DaemonService_StartInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _DaemonService_StopInstance_Handler,
		},
		{
			MethodName: "KillInstance",
			Handler:    _DaemonService_KillInstance_Handler,
		},
		{
			MethodName: "RestartInstance",
			Handler:    _DaemonService_RestartInstance_Handler,
		},
		{
			MethodName: "DeleteInstance",
			Handler:    _DaemonService_DeleteInstance_Handler,
		},
		{
			MethodName: "GetInstanceStatus",
			Handler:    _DaemonService_GetInstanceStatus_Handler,
		},
		{
			MethodName: "GetInstanceRuntime",
			Handler:    _DaemonService_GetInstanceRuntime_Handler,
		},
		{
			MethodName: "GetContainerCapability",
			Handler:    _DaemonService_GetContainerCapability_Handler,
		},
		{
			MethodName: "SetInstanceContainer",
			Handler:    _DaemonService_SetInstanceContainer_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _DaemonService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _DaemonService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _DaemonService_WriteFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _DaemonService_DeleteFile_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _DaemonService_Mkdir_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _DaemonService_RenameFile_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _DaemonService_CopyFile_Handler,
		},
		{
			MethodName: "SearchFiles",
			Handler:    _DaemonService_SearchFiles_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _DaemonService_GetMetrics_Handler,
		},
		{
			MethodName: "SubmitJob",
			Handler:    _DaemonService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _DaemonService_GetJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _DaemonService_CancelJob_Handler,
		},
		{
			MethodName: "GetPlayerOverview",
			Handler:    _DaemonService_GetPlayerOverview_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _DaemonService_SendCommand_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _DaemonService_ListResources_Handler,
		},
		{
			MethodName: "UploadResource",
			Handler:    _DaemonService_UploadResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _DaemonService_DeleteResource_Handler,
		},
		{
			MethodName: "ListJavaRuntimes",
			Handler:    _DaemonService_ListJavaRuntimes_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _DaemonService_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _DaemonService_SetConfig_Handler,
		},
		{
			MethodName: "UploadJar",
			Handler:    _DaemonService_UploadJar_Handler,
		},
		{
			MethodName: "SetInstanceJar",
			Handler:    _DaemonService_SetInstanceJar_Handler,
		},
		{
			MethodName: "ListJars",
			Handler:    _DaemonService_ListJars_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _DaemonService_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _DaemonService_Restore_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _DaemonService_ListBackups_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _DaemonService_DeleteBackup_Handler,
		},
		{
			MethodName: "ApplyTunnel",
			Handler:    _DaemonService_ApplyTunnel_Handler,
		},
		{
			MethodName: "RemoveTunnel",
			Handler:    _DaemonService_RemoveTunnel_Handler,
		},
		{
			MethodName: "ListTunnels",
			Handler:    _DaemonService_ListTunnels_Handler,
		},
		{
			MethodName: "TestFrps",
			Handler:    _DaemonService_TestFrps_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Console",
			Handler:       _DaemonService_Console_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _DaemonService_StreamMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _DaemonService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetInstanceIcon",
			Handler:       _DaemonService_GetInstanceIcon_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mcpanel.proto",
}
